on:
  push:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: 'Run Tests'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: test
        env:
          robloSecurity: ${{ secrets.ROBLOSECURITY }}
        run: mvn test -DrobloSecurity=${{ env.robloSecurity }}
