on:
  push:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: 'Run Tests'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: mvn test "-DrobloSecurity=${{ env.robloSecurity }}"
        env:
          robloSecurity: ${{ secrets.ROBLOSECURITY }}
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.7.0
        with:
          generate-coverage-badge: true
          generate-branches-badge: true